// Legacy icons (old pattern, default exports)
export { default as IconSearch } from "./IconSearch/IconSearch";
export { default as IconClear } from "./IconClear/IconClear";
export { default as IconDropdown } from "./IconDropdown/IconDropdown";
export { default as IconError } from "./IconError/IconError";
export { default as IconInfo } from "./IconInfo/IconInfo";
export { default as IconLock } from "./IconLock/IconLock";
export { default as IconSuccess } from "./IconSuccess/IconSuccess";
export { default as IconUser } from "./IconUser/IconUser";
export { default as IconX } from "./IconX/IconX";
export { default as IconPlus } from "./IconPlus/IconPlus";
export { default as IconOut } from "./IconOut/IconOut";
export { default as IconLeft } from "./IconLeft/IconLeft";
export { default as IconChild } from "./IconChild/IconChild";
export { default as IconHeart } from "./IconHeart/IconHeart";
export { default as IconSpinner } from "./IconSpinner/IconSpinner";
export { default as IconDate } from "./IconDate/IconDate";
export { default as IconCheck } from "./IconCheck/IconCheck";
export { default as IconArrowCircle } from "./IconArrowCircle/IconArrowCircle";
export { default as IconTime } from "./IconTime/IconTime";
export { default as IconEye } from "./IconEye";
export { default as IconEyeOff } from "./IconEyeOff/IconEyeOff";
export { default as IconStar } from "./IconStar/IconStar";
export { default as IconMinus } from "./IconMinus/IconMinus";
export { default as IconAttention } from "./IconAttention/IconAttention";
export { default as IconPlusInverted } from "./IconPlusInverted/IconPlusInverted";

// New icons (createIcon pattern)
// Arrows
export { IconArrowLeft } from "./IconArrowLeft/IconArrowLeft";
export { IconArrowRight } from "./IconArrowRight/IconArrowRight";
export { IconArrowUp } from "./IconArrowUp/IconArrowUp";
export { IconArrowDown } from "./IconArrowDown/IconArrowDown";
export { IconChevronLeft } from "./IconChevronLeft/IconChevronLeft";
export { IconChevronRight } from "./IconChevronRight/IconChevronRight";
export { IconChevronUp } from "./IconChevronUp/IconChevronUp";
export { IconChevronDown } from "./IconChevronDown/IconChevronDown";
export { IconDoubleArrowLeft } from "./IconDoubleArrowLeft/IconDoubleArrowLeft";
export { IconDoubleArrowRight } from "./IconDoubleArrowRight/IconDoubleArrowRight";
export { IconDoubleArrowUp } from "./IconDoubleArrowUp/IconDoubleArrowUp";
export { IconDoubleArrowDown } from "./IconDoubleArrowDown/IconDoubleArrowDown";
export { IconTriangleArrowLeft } from "./IconTriangleArrowLeft/IconTriangleArrowLeft";
export { IconTriangleArrowRight } from "./IconTriangleArrowRight/IconTriangleArrowRight";
export { IconTriangleArrowUp } from "./IconTriangleArrowUp/IconTriangleArrowUp";
export { IconTriangleArrowDown } from "./IconTriangleArrowDown/IconTriangleArrowDown";
export { IconTriangleArrowsUpAndDown } from "./IconTriangleArrowsUpAndDown/IconTriangleArrowsUpAndDown";
export { IconFullscreen } from "./IconFullscreen/IconFullscreen";
export { IconFullscreenExit } from "./IconFullscreenExit/IconFullscreenExit";
export { IconDownload } from "./IconDownload/IconDownload";
export { IconUpload } from "./IconUpload/IconUpload";
export { IconSort } from "./IconSort/IconSort";
export { IconSortingAscending } from "./IconSortingAscending/IconSortingAscending";
export { IconSortingDescending } from "./IconSortingDescending/IconSortingDescending";
export { IconSwap } from "./IconSwap/IconSwap";
export { IconIncrease } from "./IconIncrease/IconIncrease";
export { IconDecrease } from "./IconDecrease/IconDecrease";
export { IconRepost } from "./IconRepost/IconRepost";

// Navigations
export { Icon3dReview } from "./Icon3dReview/Icon3dReview";
export { IconAllProducts } from "./IconAllProducts/IconAllProducts";
export { IconCatalog } from "./IconCatalog/IconCatalog";
export { IconCatalogSearch } from "./IconCatalogSearch/IconCatalogSearch";
export { IconCheckInCircle } from "./IconCheckInCircle/IconCheckInCircle";
export { IconCustomization } from "./IconCustomization/IconCustomization";
export { IconDragAndDrop } from "./IconDragAndDrop/IconDragAndDrop";
export { IconDraggable } from "./IconDraggable/IconDraggable";
export { IconHorizontalScroll } from "./IconHorizontalScroll/IconHorizontalScroll";
export { IconInfoCircle } from "./IconInfoCircle/IconInfoCircle";
export { IconInfoSign } from "./IconInfoSign/IconInfoSign";
export { IconLayers } from "./IconLayers/IconLayers";
export { IconMenu } from "./IconMenu/IconMenu";
export { IconMore } from "./IconMore/IconMore";
export { IconParameters } from "./IconParameters/IconParameters";
export { IconQuestion } from "./IconQuestion/IconQuestion";
export { IconQuestionCircle } from "./IconQuestionCircle/IconQuestionCircle";
export { IconTechInfo } from "./IconTechInfo/IconTechInfo";
export { IconVerticalScroll } from "./IconVerticalScroll/IconVerticalScroll";
export { IconViewCard } from "./IconViewCard/IconViewCard";
export { IconViewLargeGrid } from "./IconViewLargeGrid/IconViewLargeGrid";
export { IconViewSmallGrid } from "./IconViewSmallGrid/IconViewSmallGrid";
export { IconViewTable } from "./IconViewTable/IconViewTable";
export { IconWarning } from "./IconWarning/IconWarning";
export { IconWarningCircle } from "./IconWarningCircle/IconWarningCircle";

// Objects
export { IconApplications } from "./IconApplications/IconApplications";
export { IconAudiobook } from "./IconAudiobook/IconAudiobook";
export { IconAvailability } from "./IconAvailability/IconAvailability";
export { IconBag } from "./IconBag/IconBag";
export { IconBeta } from "./IconBeta/IconBeta";
export { IconBook } from "./IconBook/IconBook";
export { IconBusiness } from "./IconBusiness/IconBusiness";
export { IconCalendar } from "./IconCalendar/IconCalendar";
export { IconCar } from "./IconCar/IconCar";
export { IconCompany } from "./IconCompany/IconCompany";
export { IconDayMode } from "./IconDayMode/IconDayMode";
export { IconDelivery } from "./IconDelivery/IconDelivery";
export { IconDevelopersMode } from "./IconDevelopersMode/IconDevelopersMode";
export { IconDevices } from "./IconDevices/IconDevices";
export { IconDocument } from "./IconDocument/IconDocument";
export { IconDvrCamera } from "./IconDvrCamera/IconDvrCamera";
export { IconFlag } from "./IconFlag/IconFlag";
export { IconFlashCard } from "./IconFlashCard/IconFlashCard";
export { IconGavel } from "./IconGavel/IconGavel";
export { IconGeo } from "./IconGeo/IconGeo";
export { IconHalfDayMode } from "./IconHalfDayMode/IconHalfDayMode";
export { IconHalfStar } from "./IconHalfStar/IconHalfStar";
export { IconHeadphones } from "./IconHeadphones/IconHeadphones";
export { IconHelp } from "./IconHelp/IconHelp";
export { IconHome } from "./IconHome/IconHome";
export { IconIncognito } from "./IconIncognito/IconIncognito";
export { IconKeyboard } from "./IconKeyboard/IconKeyboard";
export { IconLink } from "./IconLink/IconLink";
export { IconLoudspeaker } from "./IconLoudspeaker/IconLoudspeaker";
export { IconMapTag } from "./IconMapTag/IconMapTag";
export { IconMonitor } from "./IconMonitor/IconMonitor";
export { IconMts } from "./IconMts/IconMts";
export { IconMusic } from "./IconMusic/IconMusic";
export { IconNightMode } from "./IconNightMode/IconNightMode";
export { IconNotificationBell } from "./IconNotificationBell/IconNotificationBell";
export { IconNotificationOff } from "./IconNotificationOff/IconNotificationOff";
export { IconOpenBook } from "./IconOpenBook/IconOpenBook";
export { IconPicture } from "./IconPicture/IconPicture";
export { IconPresent } from "./IconPresent/IconPresent";
export { IconPress } from "./IconPress/IconPress";
export { IconQr } from "./IconQr/IconQr";
export { IconRadio } from "./IconRadio/IconRadio";
export { IconRemoteControl } from "./IconRemoteControl/IconRemoteControl";
export { IconSettingsGear } from "./IconSettingsGear/IconSettingsGear";
export { IconShield } from "./IconShield/IconShield";
export { IconShieldCheck } from "./IconShieldCheck/IconShieldCheck";
export { IconShoppingCart } from "./IconShoppingCart/IconShoppingCart";
export { IconSpace } from "./IconSpace/IconSpace";
export { IconSpeaker } from "./IconSpeaker/IconSpeaker";
export { IconStarIcon } from "./IconStarIcon/IconStarIcon";
export { IconThunderbolt } from "./IconThunderbolt/IconThunderbolt";
export { IconTimer } from "./IconTimer/IconTimer";
export { IconTool } from "./IconTool/IconTool";
export { IconVentilation } from "./IconVentilation/IconVentilation";
export { IconWaiting } from "./IconWaiting/IconWaiting";

// Actions
export { IconAddAttachment } from "./IconAddAttachment/IconAddAttachment";
export { IconAddLink } from "./IconAddLink/IconAddLink";
export { IconArchive } from "./IconArchive/IconArchive";
export { IconAttachment } from "./IconAttachment/IconAttachment";
export { IconAutoTheme } from "./IconAutoTheme/IconAutoTheme";
export { IconBackspace } from "./IconBackspace/IconBackspace";
export { IconBookmark } from "./IconBookmark/IconBookmark";
export { IconBookmarkAdd } from "./IconBookmarkAdd/IconBookmarkAdd";
export { IconBookmarkRemove } from "./IconBookmarkRemove/IconBookmarkRemove";
export { IconCamera } from "./IconCamera/IconCamera";
export { IconCheckCircle } from "./IconCheckCircle/IconCheckCircle";
export { IconCloudDone } from "./IconCloudDone/IconCloudDone";
export { IconCloudDownloading } from "./IconCloudDownloading/IconCloudDownloading";
export { IconCompare } from "./IconCompare/IconCompare";
export { IconCopy } from "./IconCopy/IconCopy";
export { IconCross } from "./IconCross/IconCross";
export { IconCrossCircle } from "./IconCrossCircle/IconCrossCircle";
export { IconCut } from "./IconCut/IconCut";
export { IconDelete } from "./IconDelete/IconDelete";
export { IconDislike } from "./IconDislike/IconDislike";
export { IconDownloadCircle } from "./IconDownloadCircle/IconDownloadCircle";
export { IconEdit } from "./IconEdit/IconEdit";
export { IconEntrance } from "./IconEntrance/IconEntrance";
export { IconEraser } from "./IconEraser/IconEraser";
export { IconExit } from "./IconExit/IconExit";
export { IconFileOnCloud } from "./IconFileOnCloud/IconFileOnCloud";
export { IconFileOnDevice } from "./IconFileOnDevice/IconFileOnDevice";
export { IconFilter } from "./IconFilter/IconFilter";
export { IconFilterAlternative } from "./IconFilterAlternative/IconFilterAlternative";
export { IconFilterOff } from "./IconFilterOff/IconFilterOff";
export { IconFitToScreen } from "./IconFitToScreen/IconFitToScreen";
export { IconGroup } from "./IconGroup/IconGroup";
export { IconHeadlightsOn } from "./IconHeadlightsOn/IconHeadlightsOn";
export { IconHeartAction } from "./IconHeartAction/IconHeartAction";
export { IconHeartAdd } from "./IconHeartAdd/IconHeartAdd";
export { IconHeartBroken } from "./IconHeartBroken/IconHeartBroken";
export { IconHeartRemove } from "./IconHeartRemove/IconHeartRemove";
export { IconHide } from "./IconHide/IconHide";
export { IconLike } from "./IconLike/IconLike";
export { IconLockAction } from "./IconLockAction/IconLockAction";
export { IconMinusAction } from "./IconMinusAction/IconMinusAction";
export { IconMinusCircle } from "./IconMinusCircle/IconMinusCircle";
export { IconMobileScreenshot } from "./IconMobileScreenshot/IconMobileScreenshot";
export { IconObjectsGroup } from "./IconObjectsGroup/IconObjectsGroup";
export { IconOk } from "./IconOk/IconOk";
export { IconOpenInNew } from "./IconOpenInNew/IconOpenInNew";
export { IconPause } from "./IconPause/IconPause";
export { IconPin } from "./IconPin/IconPin";
export { IconPlay } from "./IconPlay/IconPlay";
export { IconPlusAction } from "./IconPlusAction/IconPlusAction";
export { IconPlusCircle } from "./IconPlusCircle/IconPlusCircle";
export { IconPower } from "./IconPower/IconPower";
export { IconPrint } from "./IconPrint/IconPrint";
export { IconReply } from "./IconReply/IconReply";
export { IconResetSettings } from "./IconResetSettings/IconResetSettings";
export { IconRotateLeft } from "./IconRotateLeft/IconRotateLeft";
export { IconRotateRight } from "./IconRotateRight/IconRotateRight";
export { IconRotateTheDevice } from "./IconRotateTheDevice/IconRotateTheDevice";
export { IconSave } from "./IconSave/IconSave";
export { IconScan } from "./IconScan/IconScan";
export { IconScanBarcode } from "./IconScanBarcode/IconScanBarcode";
export { IconScanCard } from "./IconScanCard/IconScanCard";
export { IconScanMethod } from "./IconScanMethod/IconScanMethod";
export { IconScanQr } from "./IconScanQr/IconScanQr";
export { IconSearchAction } from "./IconSearchAction/IconSearchAction";
export { IconSelectFrameHorizontal } from "./IconSelectFrameHorizontal/IconSelectFrameHorizontal";
export { IconSelectFrameSquare } from "./IconSelectFrameSquare/IconSelectFrameSquare";
export { IconSelectFrameVertical } from "./IconSelectFrameVertical/IconSelectFrameVertical";
export { IconShare } from "./IconShare/IconShare";
export { IconShift } from "./IconShift/IconShift";
export { IconShow } from "./IconShow/IconShow";
export { IconStop } from "./IconStop/IconStop";
export { IconUngroup } from "./IconUngroup/IconUngroup";
export { IconUnlock } from "./IconUnlock/IconUnlock";
export { IconUpdate } from "./IconUpdate/IconUpdate";
export { IconUploadCircle } from "./IconUploadCircle/IconUploadCircle";

// Social Networks
export { IconBehance } from "./IconBehance/IconBehance";
export { IconDzen } from "./IconDzen/IconDzen";
export { IconOdnoklassniki } from "./IconOdnoklassniki/IconOdnoklassniki";
export { IconTelegram } from "./IconTelegram/IconTelegram";
export { IconTiktok } from "./IconTiktok/IconTiktok";
export { IconViber } from "./IconViber/IconViber";
export { IconVk } from "./IconVk/IconVk";
export { IconWhatsapp } from "./IconWhatsapp/IconWhatsapp";
export { IconYoutube } from "./IconYoutube/IconYoutube";
