export const allowedDomains = new Set([
  "urent.ru",
  "ticketscloud.com",
  "greendc.ru",
  "bronevik.com",
  "gulfstream.ru",
  "mts.ru",
  "mts.am",
  "mts.by",
  "mtsretail.ru",
  "metro-telecom.ru",
  "mgts.ru",
  "mts-energo.ru",
  "rstudios.ru",
  "ponominalu.ru",
  "stopol-auto.com",
  "litebox.ru",
  "mtsbank.ru",
  "ticketland.ru",
  "it-grad.ru",
  "zelenaya.net",
  "mtt.ru",
  "comdi.com",
  "webinar.ru",
  "iformula.ru",
  "cc.zelenaya.net",
  "mtrend.ru",
  "elista.zelenaya.net",
  "gorodtv.net",
  "tambov.zelenaya.net",
  "vladivostok.zelenaya.net",
  "belgorod.zelenaya.net",
  "lipezk.zelenaya.net",
  "tomsk.zelenaya.net",
  "ufa.zelenaya.net",
  "visionlabs.ai",
  "nov.mts.ru",
  "exolve.ru",
  "skai.online",
  "mts-link.ru",
  "ekb.gulfstream.ru",
  "krd.gulfstream.ru",
  "krk.gulfstream.ru",
  "kzn.gulfstream.ru",
  "nn.gulfstream.ru",
  "nsb.gulfstream.ru",
  "oms.gulfstream.ru",
  "prm.gulfstream.ru",
  "rst.gulfstream.ru",
  "sch.gulfstream.ru",
  "sip.gulfstream.ru",
  "smartsafety.dev",
  "smr.gulfstream.ru",
  "sochi.gulfstream.ru",
  "spb.gulfstream.ru",
  "srv.gulfstream.ru",
  "yar.gulfstream.ru",
  "weareathome.ru",
  "vrz.gulfstream.ru",
  "vgd.gulfstream.ru",
  "ufa.gulfstream.ru",
  "tul.gulfstream.ru",
  "tmn.gulfstream.ru",
  "exibank.ru",
  "exi-bank.ru",
  "urent.city",
  "buzzoola.com",
  "getblogger.ru",
  "segmento.ru",
  "mws.ru",
  "deep-agency.ru",
  "mediascout.ru",
  "capital.com",
  "entrustment.ru",
]);

export const isEmailAllowed = (email: string): boolean => {
  const parts = email.toLowerCase().trim().split("@");
  if (parts.length !== 2) return false;
  return allowedDomains.has(parts[1]);
};

export const russianLettersPattern = /^[а-яА-ЯёЁ\s\-']+$/;
